// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://naczwampjdgumcwfkdhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hY3p3YW1wamRndW1jd2ZrZGh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MzI0ODMsImV4cCI6MjA3NDQwODQ4M30.q7kJd811cdNVmUC-eJYgc3Mq5ifON3Rsn-OHJa7TXRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});